[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.5",
    "fastapi>=0.115.12",
    "pymysql>=1.1.1",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.34.2",
]
